## Numpy
- Mathematics package
- released in 1995 
- random numbers, math package, arrays, Null values , matrix, linear algebra, datatypes check...........................


In [2]:
import numpy

In [74]:
# print( dir(numpy) )

In [11]:
# basic math

import math

num = 50
print( f"Squareroot -> {math.sqrt(num)}" )
print( f"Log -> {math.log(num)}" )
print( f"Sin -> {math.sin(num)}" )


print("**" * 20)

import numpy

num = 50
print( f"Squareroot -> {numpy.sqrt(num)}" )
print( f"Log -> {numpy.log(num)}" )
print( f"Sin -> {numpy.sin(num)}" )


Squareroot -> 7.0710678118654755
Log -> 3.912023005428146
Sin -> -0.26237485370392877
****************************************
Squareroot -> 7.0710678118654755
Log -> 3.912023005428146
Sin -> -0.26237485370392877


In [70]:
# random 

import random

print( random.random() )
print( random.randint(1 , 10) )
print( random.sample( (1 , 5 , 7 , 3 , 7 , 10 , -5 , -9 , -1) , 3 ) )

print("**" * 20)

import numpy


print( numpy.random.random() )
print( numpy.random.randint(1 , 10) )
# print( numpy.random.random_sample(  )



0.6504440120079112
2
[-5, -1, 7]
****************************************
0.6153913946575693
2


In [72]:
# Stats

import numpy 

listName = [1 , 5 , 7 , 3 , 7 , 10 , -5 , -9 , -1]

print(  numpy.max(listName) )
print(  numpy.min(listName) )
print(  numpy.std(listName) )
print(  numpy.mean(listName) )
print(  numpy.median(listName) )
print(  numpy.sum(listName) )


10
-9
5.811865258054231
2.0
3.0
18


In [88]:
# Data Types

import numpy

print( False == numpy.bool_ ) 

False


In [92]:
numpy.nan 

nan

# Numpy Arrays

- collection of same datatypes
- immutable
- ordered


In [96]:
import numpy

arr = numpy.array( [10 , 6 , 7 , 6 , -4] )
seq = [10 , 6 , 7 , 6 , -4]

print( arr )
print( type( arr ) )

print( seq )
print( type( seq ) )


[10  6  7  6 -4]
<class 'numpy.ndarray'>
[10, 6, 7, 6, -4]
<class 'list'>


In [101]:
# precedence order -> str, complex , float, inte, bool

arr = numpy.array( [6.44 , 7j , 6 , -4, True, "delhi"] )

print( arr )
print( type( arr ) )

print("*" * 10)

arr = numpy.array( [6.44 , 7j , 6 , -4, True] )
print( arr )
print( type( arr ) )

print("*" * 10)

arr = numpy.array( [6.44 , 6 , -4, True] )
print( arr )
print( type( arr ) )

print("*" * 10)

arr = numpy.array( [ 6 , -4, True] )
print( arr )
print( type( arr ) )

print("*" * 10)

arr = numpy.array( [True] )
print( arr )
print( type( arr ) )

print("*" * 10)



['6.44' '7j' '6' '-4' 'True' 'delhi']
<class 'numpy.ndarray'>
**********
[ 6.44+0.j  0.  +7.j  6.  +0.j -4.  +0.j  1.  +0.j]
<class 'numpy.ndarray'>
**********
[ 6.44  6.   -4.    1.  ]
<class 'numpy.ndarray'>
**********
[ 6 -4  1]
<class 'numpy.ndarray'>
**********
[ True]
<class 'numpy.ndarray'>
**********


In [11]:
import numpy

arr = numpy.array( [True, False] )
print(arr)



[ True False]


In [102]:
seq = [6.44 , 7j , 6 , -4, True, "delhi"] 

print( seq )
print( type( seq ) )


[6.44, 7j, 6, -4, True, 'delhi']
<class 'list'>


In [12]:
a = numpy.array( [6.44 , 7j , 6 , -4, True, "delhi"] )

print(a[1:5:2])

['7j' '-4']


In [112]:
arr = numpy.array( [6.44 , 7j , 6 , -4, True, "delhi"] )

print( arr )
print( type( arr ) )
print( len( arr ) )

# Index
print( arr[1] )
print( arr[-1] )

# Slice
print( arr[0 : 3] )
print( arr[1 : 5 : 2] )

# membership
print( 100 in arr )
print( 'delhi' in arr )


['6.44' '7j' '6' '-4' 'True' 'delhi']
<class 'numpy.ndarray'>
6
7j
delhi
['6.44' '7j' '6']
['7j' '-4']
False
True


C:\Users\Nitish\AppData\Local\Temp\ipykernel_1696\195438466.py:14: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  print( 100 in arr )


In [109]:
# no repeat. actual its array multuplications

arr = numpy.array( [1 , 3] )
print( arr * 3 )

[3 9]


In [110]:
# no cocnat. actual its array sum

a1 = numpy.array( [10, 20] )
a2 = numpy.array( [-5, -5] )

print( a1 + a2 )

[ 5 15]


In [114]:
print( dir(arr) )

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [ ]:
# 

In [ ]:
# Array transpose, dot multiplications, determinant

In [116]:
numpy.linspace( 1 , 10, num = 5 )

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])